### ISSUE TITLE
В кредитном счете, при пополнении с не нулевым балансом, не учитывается баланс до пополнения

### ISSUE THREAD

**Issue by Kanger79** [Kanger79/TeamProject_QA-60#1]
## Описание
При пополнении кредитного счета с не нулевым балансом, сумма пополнения не прибавляется к текущему (до пополнения) балансу, а заменяет его. 

## Локация дефекта:

https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L70

## Шаги по воспроизведению

1. Открыть проект в **IntellijIDEA**.
2. Перейти в класс [*CreditAccountTest*](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) .
3. Создать тест **shouldAddToPositiveBalance**, в котором указать следующие параметры:
  3.1. Создание объекта *account* класса `CreditAccount`.
  3.2. Начальный баланс объекта 1000р.
  3.3. Кредитный лимит 5000р.
  3.4. Процентная ставка 15.
  3.5. Метод пополнения, на сумму 4000р.
   
![Issues_01_2](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/2c11680e-19eb-4eda-872f-6fd5f8292f53)

4. Совершить пополнение на сумму 4000р. (запустить тест **shouldAddToPositiveBalance**)

## Ожидаемый результат
Баланс на счете увеличился на 4000 и стал равен 5000.

## Фактический результат
Баланс на счете стал равен сумме пополнения 4000.

## Скриншот

![Issues_01_1](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/d03f90da-1f82-4fdc-a955-71b7b6a64ac6)

https://github.com/Kanger79/TeamProject_QA-60/blob/3b5596d125ff745b46b5578e0de6fc89d6a3a3cd/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L23-L36

## Окружение

* **Операционная система:** Windows 10 LTSC
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nik8808** [comment]
В классе CreditAccount, в методе add добавлено условие:
https://github.com/Kanger79/TeamProject_QA-60/blob/61f8b64d3ddfdf24adac0827a42d0606503ece9a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L73
