### ISSUE TITLE
В сберегательном счете, при пополнении баланс становится равен сумме пополнения

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#10]
# Описание

В классе SavingAccount, операция пополнение не прибавляет к балансу сумму пополнения, а становиться равна этой сумме.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68-L76

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L128-L138)
2. Создать тест replenishmentSuccessfully со следующими параметрами: начальный баланс 2000, минимальным балансом 1000, максимальным балансом 6000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/64569312-36f6-42f1-864e-e44fd15ce9b2)
1. Совершить пополнение на 3000.

## *Ожидаемый результат:* 
Баланс увеличится на сумму пополнения и стал равен 5000
## *Фактический результат:* 
Баланс стал равен сумме пополнения
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/72d08a28-d53f-46f8-ba96-1269e4c103b9)
https://github.com/Kanger79/TeamProject_QA-60/blob/58694346ca811191662abf46241b56d512be6a45/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L128-L138

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount**, методе **add** изменен код: 
https://github.com/Kanger79/TeamProject_QA-60/blob/27d7c746db67f9593999727bac3762b2f7f8440a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L78
