### ISSUE TITLE
В кредитном счете начальный баланс может принимать отрицательное значение

### ISSUE THREAD

**Issue by Kanger79** [Kanger79/TeamProject_QA-60#11]
## Описание
В кредитном счете начальный баланс может принимать отрицательное значение, что противоречит условию задания

## Локация дефекта:

https://github.com/Kanger79/TeamProject_QA-60/blob/61f8b64d3ddfdf24adac0827a42d0606503ece9a/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L21-L30

## Шаги по воспроизведению
1. Открыть проект в IntellijIDEA.
2. Перейти в класс [*CreditAccountTest*](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) .
3. Создать тест **negativeInitialBalance**, в котором указать следующие параметры:
  3.1. Алгоритм проверки наличия исключения объекта класса `CreditAccount` с  начальным балансом -4000р, кредитным лимитом 3000р и процентной ставкой 15.
  
![Issues_11_1](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/e2c86792-6f68-475b-ae02-77ce6e20cb57)

4. С помощью алгоритма, проверить наличие исключения для класса `CreditAccount` в случае, когда начальный баланс принимает отрицательное значение. (запустить тест **negativeInitialBalance**)

### Ожидаемый результат
Алгоритм проверки наличия исключения определил ситуацию с отрицательным начальным балансом как исключительную и вывел соответствующее сообщение.

### Фактический результат

Из-за отсутствия условия, определяющего исключение в классе `CreditAccount` начальный баланс принимает отрицательное значение.

### Скриншот

![Issues_11_2](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/3eaff8aa-5589-498c-9c5a-6e54f767ec10)

https://github.com/Kanger79/TeamProject_QA-60/blob/1ca9ff00052df088a567e73a8cd7c8f760656058/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L132-L142

### Окружение

* **Операционная система:** Windows 10 LTSC
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nik8808** [comment]
В классе CreditAccount, добавил исключение
https://github.com/Kanger79/TeamProject_QA-60/blob/1ca9ff00052df088a567e73a8cd7c8f760656058/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L27-L29

**Comment by Kanger79** [comment]
Спасибо! Всё ОК! закрываю репорт..
