### ISSUE TITLE
В сберегательном счете, оплата не выполняется если ее результат равен минимальному балансу

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#12]
# Описание

В классе SavingAccount метод оплаты не выполняется если результат равен минимальному балансу.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L52
# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L100-L110](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L71-L82))
2. Создать тест paymentPassedAmountEqualToMinсо следующими параметрами: начальный баланс 5000, минимальным балансом 1000, максимальным балансом 10000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/4168adcc-004d-4fa0-b2b0-1d0599fe1410)
1. Совершить покупку (платеж) на 4000.

## *Ожидаемый результат:* 
Покупка (платеж) совершена, баланс на счете уменьшился на сумму покупки и стал равен минимальному (1000).

## *Фактический результат:* 
Покупка (платеж) не совершена, баланс  на счете не изменился.

# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/4543bbbb-687f-49f3-9f09-0388d971e4fc)
https://github.com/Kanger79/TeamProject_QA-60/blob/2cfd3a2d3d6121f81b5f127fc4fd252ab73ce51a/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L100-L110

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount**, в методе **pay**, изменено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/514d081237b8d1a3e04508846987f7ce9760aabf/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L66-L76

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
