### ISSUE TITLE
В классе Bank, при соблюдении условий первого счета, осуществляется перевод (списание) на второй, у которого есть ограничения, из-за чего перевод не поступает. При этом операция считается успешной.

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#13]
# Описание

В классе Bank, при транзакции со счета списание, деньги уходят но не приходят на счет получателя из-за ограничения второго. Операция считается успешной
# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/Bank.java#L20-L21

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [BankTest](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/BankTest.java#L121-L128)
2. Создать тест transferBetweenCreditAndSavingsAccountMaximumBalanceExceeded со следующими параметрами: Создаем кредитный счёт с которого переводим с начальный баланс 0, кредитный лимит 5000, процент по кредиту 15. Дебетовый счет на который переводим с начальным балансом 5000, минимальным балансом 1000, максимальным балансом 9000, процентной ставкой 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/36a04a3a-7d23-4a27-882a-de552a301fa2)
1. Совершить перевод на 5000.

## *Ожидаемый результат:* 
Операция по переводу не совершена, балансы счетов не изменились.
## *Фактический результат:* 
Со счета плательщика переводимая сумма списалась, но на счет получателя не поступила.
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/800d7239-181f-41a7-8b96-0a8a1a0504ee)
https://github.com/Kanger79/TeamProject_QA-60/blob/0a8506fd8085301bfa8f23f9693af16623c76ead/src/test/java/ru/netology/javaqadiplom/BankTest.java#L121-L128

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **Bank**, в методе **transfer** добавлено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/73c2b6b872a286db11ef79c37bf247746bcd4fbd/src/main/java/ru/netology/javaqadiplom/Bank.java#L24-L27

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
