### ISSUE TITLE
В классе Bank, любая положительная (и не нулевая) операция считается успешной. Даже если она не совершена из-за ограничений.

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#14]
# Описание

В классе Bank, любая операция считается успешной кроме когда сумма перевода меньше или равна нулю. Даже если операции по списанию и пополнению не выполнялись.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/Bank.java#L16-L23

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [BankTest](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/BankTest.java#L17-L24)
2. Создать тест transferBetweenSavingsAccountsFailedDueToFirstAccount со следующими параметрами: Создаем дебетовый счёт с которого переводим с начальным балансом 5000, минимальным балансом 1000, максимальным балансом 10000, процентной ставкой 5. Дебетовый счет на который переводим с начальным балансом 5000, минимальным балансом 1000, максимальным балансом 10000, процентной ставкой 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/3af3db08-6bb2-4d12-a245-060ea638b16f)
1. Совершить перевод на 5000.

## *Ожидаемый результат:* 
Операция по переводу false. Перевод не прошел
## *Фактический результат:* 
Операция по переводу true. Операция считается успешной. Но перевод не прошел.
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/2cfa74fd-015c-4d87-9973-ab117dea2f3b)
https://github.com/Kanger79/TeamProject_QA-60/blob/0a8506fd8085301bfa8f23f9693af16623c76ead/src/test/java/ru/netology/javaqadiplom/BankTest.java#L17-L24

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
1. В классе **Bank**, методе **transfer** добавлено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/73c2b6b872a286db11ef79c37bf247746bcd4fbd/src/main/java/ru/netology/javaqadiplom/Bank.java#L21-L23

2. В классе **Bank**, в методе **transfer** удалено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/73c2b6b872a286db11ef79c37bf247746bcd4fbd/src/main/java/ru/netology/javaqadiplom/Bank.java#L28-L30

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
