### ISSUE TITLE
В сберегательном счете, при балансе меньше 100, не рассчитывается процент начисления

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#19]
# Описание

В классе SavingAccount, из-за особенности целочисленного деления, при балансе меньше 100 и высокой процентной ставке, начисления по процентам не насчитываются.
# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/36f311ccae4599e1517fa91dc29028c692299029/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L113-L115

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L29-L34)
2. Создать тест interestOnTheBalance со следующими параметрами: начальный баланс 99, минимальным балансом 10, максимальным балансом 10000, процентная ставка 80
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/feb95f63-dc1d-44b5-a121-f3bfbe1a7305)
1. Совершить расчет процентов на остаток.

## *Ожидаемый результат:* 
Сумма процента на остаток равно 80.
## *Фактический результат:* 
Сумма процентов на остаток равна 0
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/f7a07d37-8195-4dc3-9ce0-8ad7f6abd11f)

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount**, в методе расчета процентной ставке (**yearChange**) изменен порядок математических операций:

https://github.com/Kanger79/TeamProject_QA-60/blob/96b38405702cbf77c9c642ec9ece39130ad02434/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L113-L116
