### ISSUE TITLE
В кредитном счете, после покупки, баланс принимает отрицательное значение стоимости покупки

### ISSUE THREAD

**Issue by Kanger79** [Kanger79/TeamProject_QA-60#2]
### Описание
В кредитном счете, после совершения покупки, баланс принимает значение стоимости покупки со знаком "минус".

### Локация дефекта:

https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

### Шаги по воспроизведению
1. Открыть проект в **IntellijIDEA**.
2. Перейти в класс [*CreditAccountTest*](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) .
3. Создать тест **payPositiveBalanceLessCreditLimit**, в котором указать следующие параметры:
  3.1. Создание объекта *account* класса `CreditAccount`.
  3.2. Начальный баланс объекта 4000р.
  3.3. Кредитный лимит 3000р.
  3.4. Процентная ставка 15.
  3.5. Метод покупки, на сумму 1000р.

![Issues_02_1_pay](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/afbff36b-0eff-4719-bcfb-ed44b6eb535c)

4. Совершить покупку на 1000р. (запустить тест **payPositiveBalanceLessCreditLimit**)

### Ожидаемый результат
Баланс уменьшился на стоимость покупки и стал равен **3000**.

### Фактический результат
Баланс на счете стал равен отрицательному значению стоимости покупки **-1000**.

### Скриншот

![Issues_02_2_pay](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/ca8ec621-306f-465f-b257-6d0cef96011c)

### Окружение

* **Операционная система:** Windows 10 LTSC
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nik8808** [comment]
В классе CreditAccount, в методе pay исправил:
https://github.com/Kanger79/TeamProject_QA-60/blob/1cbb1cf0bd5fc7d16a45b5d72c4dfa989d1a30ad/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47-L48

**Comment by Kanger79** [comment]
Спасибо! Всё ОК.. закрываю репорт..
