### ISSUE TITLE
В сберегательном счете минимальный баланс может принять значение больше максимального баланса

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#3]
# Описание

В классе SavingAccount нет исключение что бы минимальный балансе не мог превышать максимальной баланс.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Создать тестируемый объект в классе [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#LL15C5-L20C6})
1. Создать тест **minGreaterMax** со следующими параметрами:  начальный баланс 2000, минимальным балансом 10000, максимальным балансом 5000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/8d3ffb41-6eea-4d78-8c72-3526d05a7834)

## *Ожидаемый результат:* 
Алгоритм проверки наличия исключения определил ситуацию где минимальный баланс не может быть больше максимального и вывел соответствующее сообщение.

## *Фактический результат:* 
Из-за отсутствия условия, определяющего исключение в классе SavingAccount, минимальный баланс может принимать значения больше максимального баланса

# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/d24205f7-ff08-4370-8b06-f8420557d850)
https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L15-L20
# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В метод SavingAccount добавлено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/58694346ca811191662abf46241b56d512be6a45/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L28-L32
