### ISSUE TITLE
В сберегательном счете начальный баланс может принять значение больше максимального баланса

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#4]
# Описание

В классе SavingAccount нет исключение что бы начальный баланс не мог превышать максимальной баланс.

# Локация дефекта
 https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L22-L27)
1. Создать тест bigMax со следующими параметрами: начальный баланс 15000, минимальным балансом 1000, максимальным балансом 10000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/675d698d-1366-4a13-b903-784e520b3318)

## *Ожидаемый результат:* 
Алгоритм проверки наличия исключения определил ситуацию где начальный баланс не может быть больше максимального баланса и вывел соответствующее сообщение.
## *Фактический результат:* 
Из-за отсутствия условия, определяющего исключение в классе SavingAccount, начальный баланс может быть больше максимального баланса

# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/b88f75d4-8ea7-43e0-a39c-ab9fc5061525)
https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L22-L27

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **savingAccount** добавлено условие:
https://github.com/Kanger79/TeamProject_QA-60/blob/ee26bd8d7d8dbf63f7048565864f495b7f04af96/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L33-L37

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
