### ISSUE TITLE
В сберегательном счете начальный баланс может принять значение меньше минимального баланса

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#5]
# Описание

В классе SavingAccount нет исключение что бы начальный баланс не мог быть меньше минимального баланс.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L29-L34)
2. Создать тест lessMin со следующими параметрами: начальный баланс 1000, минимальным балансом 2000, максимальным балансом 10000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/23d483a4-4eb1-46ad-b954-02cda15108d6)

## *Ожидаемый результат:* 
Алгоритм проверки наличия исключения определил ситуацию где начальный баланс не может быть меньше минимального баланса и вывел соответствующее сообщение.
## *Фактический результат:* 
Из-за отсутствия условия, определяющего исключение в классе SavingAccount, начальный баланс может быть меньше минимального баланса
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/3cf15a78-ecee-4d0a-94c1-b19aa2854b97)
https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L29-L34

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount** добавлено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/fb36456f16d79ce8fa8483e49537f32cf38a745e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L38-L42

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
