### ISSUE TITLE
В сберегательном счете минимальный баланс может принять отрицательное значение

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#6]
# Описание

В классе SavingAccount нет исключения для отрицательного минимального баланса.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L36-L41)
2. Создать тест minNegative со следующими параметрами: начальный баланс 3000, минимальным балансом -2000, максимальным балансом 5000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/04937857-d4bc-405b-b3ae-ff3924cacbfa)

## *Ожидаемый результат:* 
Алгоритм проверки наличия исключения определил ситуацию где минимальный баланс не может принимать отрицательное отрицательное значение  и вывел соответствующее сообщение.
## *Фактический результат:* 
Из-за отсутствия условия, определяющего исключение в классе SavingAccount, минимальный баланс может принимать отрицательное значение.
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/c3fed95d-c429-4166-8a61-8a146c860082)
https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L36-L41

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount** добавлено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/b515c9dcd0917d8196931cc504020269614ebac3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L48

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
