### ISSUE TITLE
В сберегательном счете, после покупки баланс может принимать значение меньше минимального баланса

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#7]
# Описание

В классе SavingAccount после покупки баланс не может быть меньше минимального баланса.

# Локация дефекта
https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L54

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44-L54)
2. Создать тест paymentFailedBalanceCannotBeLessThanMin со следующими параметрами: начальный баланс 5000, минимальным балансом 2000, максимальным балансом 10000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/f31bdcf2-bc94-45f0-9ee7-8a077d460249)
3. Совершить оплату на 4000

## *Ожидаемый результат:* 
Операция не совершена (т.к. её результатом будет нарушение нижней границы допустимого баланса),  баланс не изменился (5000).
## *Фактический результат:* 
Операция совершена, сумма баланса изменилась (1000) и стала меньше минимально разрешенного значения (2000).  
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/266a1970-b001-4c5f-9509-6b240990ec7a)
https://github.com/Kanger79/TeamProject_QA-60/blob/9d16d5cf28f34eb55a376f1d456a06b216494908/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L71-L83

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount**, в методе **pay** изменен код:

https://github.com/Kanger79/TeamProject_QA-60/blob/bb8f89d692f107347eef163c51be5fcf8bfe8a5e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L66-L75

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
