### ISSUE TITLE
В кредитном счете, расчет процентов на отрицательный баланс происходит при положительном балансе

### ISSUE THREAD

**Issue by Kanger79** [Kanger79/TeamProject_QA-60#8]
## Описание
В кредитном счете расчет процентов на отрицательный баланс происходит при положительном балансе

## Локация дефекта:

https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L85

## Шаги по воспроизведению
1. Открыть проект в IntellijIDEA.
2. Перейти в класс [*CreditAccountTest*](https://github.com/Kanger79/TeamProject_QA-60/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) .
3. Создать тест **yearChangePositiveBalance**, в котором указать следующие параметры:
  3.1. Создание объекта *account* класса `CreditAccount`.
  3.2. Начальный баланс объекта 200р.
  3.3. Кредитный лимит 3000р.
  3.4. Процентная ставка 15.
  3.5. Метод вычисления процентов на отрицательный баланс.
   
![Issues_03_1_yearChange](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/0426bc65-9800-4a80-948f-7559d1306817)

4. С помощью метода вычисления процентов на отрицательный баланс посчитать процент объекта *account* с указанными параметрами (запустить тест **yearChangePositiveBalance**)

### Ожидаемый результат
Начисление процентов при положительном балансе не производится (равно нулю).

### Фактический результат
Произведено начисление процентов при положительном балансе

### Скриншот

![Issues_03_2_yearChange](https://github.com/Kanger79/TeamProject_QA-60/assets/127352228/1cafcc4b-bf2e-44ae-b103-052ab360c25b)

https://github.com/Kanger79/TeamProject_QA-60/blob/fbd315b9758c554e2c0a18cf532c881c42f7866a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L99-L113

### Окружение

* **Операционная система:** Windows 10 LTSC
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nik8808** [comment]
В классе SavingAccount, методе yearChange изменен код:
https://github.com/Kanger79/TeamProject_QA-60/blob/54d3f9a6da134f8309cc5de9e5ec6df4c962ec41/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L86-L90

**Comment by Kanger79** [comment]
Спасибо! Всё ОК! Закрываю репорт..
