### ISSUE TITLE
В сберегательном счете, пополнение не выполняется если конечный баланс равен максимальному балансу

### ISSUE THREAD

**Issue by Nik8808** [Kanger79/TeamProject_QA-60#9]
# Описание

В классе SavingAccount пополнение не выполняется если конечный баланс равен максимальному балансу.
# Локация дефекта

https://github.com/Kanger79/TeamProject_QA-60/blob/4edc096a32ce8ffd8f102adb573a8c542e7246c9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68-L76

# Шаги воспроизведения
1. Открыть проект в IntellijIDEA.
1. Перейти в класс [SavingAccountTest](https://github.com/Kanger79/TeamProject_QA-60/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L113-L125)
2. Создать тест toppedUpByMaxAmount со следующими параметрами: начальный баланс 2000, минимальным балансом 1000, максимальным балансом 5000, процентная ставка 5
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/367e3ecc-077d-4019-94bb-5a9b0d6b5f7b)
1. Совершить пополнение на 3000.

## *Ожидаемый результат:* 
Пополнение пройдет успешно. Сумма станет равна максимальному балансу(5000).
## *Фактический результат:* 
Пополнение не прошло, баланс не поменялся
# Скриншот
![image](https://github.com/Kanger79/TeamProject_QA-60/assets/127734534/9040dcdb-81c3-494c-ad12-ab55f70c2f82)
https://github.com/Kanger79/TeamProject_QA-60/blob/58694346ca811191662abf46241b56d512be6a45/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L113-L125

# Окружение
* **Операционная система:** Майкрософт Windows 11 home
* **IDE:** Intellij IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Kanger79** [comment]
В классе **SavingAccount**, в методе **add** изменено условие:

https://github.com/Kanger79/TeamProject_QA-60/blob/2cfd3a2d3d6121f81b5f127fc4fd252ab73ce51a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L89-L100

**Comment by Nik8808** [comment]
Спасибо! Всё ОК.. закрываю репорт.
